---
- name: Create elastalert directory
  file:
    path: /etc/logstash/ssl
    state: directory
    mode: 0755
  become: true

- name: Remove default logstash config directory
  file:
    path: /etc/logstash/conf.d
    state: absent

- name: Create logstash config directory
  file:
    path: /etc/logstash/conf.d
    state: directory
    mode: 0755

- name: Copy logstash config
  template:
    src: log.conf.tpl
    dest: /etc/logstash/conf.d/log.conf
    mode: 0600
  become: true

- name: Copy logstash patterns
  copy:
    src: files/patterns
    dest: /etc/logstash
    mode: 0644

- name: Copy kibana config
  template:
    src: kibana.yml.tpl
    dest: /etc/kibana/kibana.yml
    mode: 0644
  become: true

- name: Replace elastalert config with password
  template:
    src: config.yaml.tpl
    dest: /opt/{{ ea_dir }}/config.yaml
    mode: 0644
  become: true

- name: Copy openssl config file
  template:
    src: logstash.cnf.tpl
    dest: /etc/logstash/ssl/logstash.cnf
    mode: 0644
  become: true

- name: Generate certificates
  command: "{{ generate_crt }}"
  changed_when: false
  args:
    chdir: /etc/logstash/ssl

- name: Generate pkcs8 certificate
  command: "openssl pkcs8 -in logstash.key -topk8 -out logstash8.key -nocrypt"
  changed_when: false
  args:
    chdir: /etc/logstash/ssl
